name = "monthly-collection"
main = "worker.js"
compatibility_date = "2026-09-29"

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = ["/api/*"]

[[d1_databases]]
binding = "db"
database_name = "db"
database_id = "aaca0ea2-4e76-4060-9aed-092e94412852"
migrations_dir = "migrations"
